version: "3.8"

services:
  # PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daimon_app
    working_dir: /var/www/app_beer
    environment:
      DB_DATABASE: daimon
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - .:/var/www
    networks:
      - daimon_net

  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: daimon_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: daimon
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - daimon_net

  # Nginx service
  webserver:
    image: nginx:alpine
    container_name: daimon_webserver
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - daimon_net
    expose:
    - "9000"

  phpmyadmin: # used only in development for testing, be sure to don't use it in production
    image: phpmyadmin/phpmyadmin
    container_name: daimon_phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - daimon_net

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daimon_scheduler
    restart: always
    working_dir: /var/www/
    volumes:
      - .:/var/www/
    depends_on:
      - app
    entrypoint: |
      sh -c "while [ true ]; do php /var/www/app_beer/artisan schedule:run --verbose --no-interaction; sleep 60; done"
    networks:
      - daimon_net
networks:
  daimon_net:

volumes:
  dbdata:
  esdata:
